services:
  - type: web
    name: csm-recommendations
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 120 --workers 1
    plan: free
